apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.catalog.replicas }}

  selector:
    matchLabels:
      app: catalog

  template:
    metadata:
      labels:
        app: catalog

    spec:
      containers:
        - name: catalog
          image: {{ .Values.catalog.image }}
          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.catalog.port }}

          env:
            - name: FRONTEND_SERVER
              value: frontend

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"