apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: catalog-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog

  updatePolicy:
    updateMode: "Off"

  resourcePolicy:
    containerPolicies:
    - containerName: catalog
      controlledResources:
      - cpu
      - memory