apiVersion: v1
kind: Service

metadata:
  name: order
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: order

  ports:
  - port: 80
    targetPort: {{ .Values.order.port }}

  type: NodePort
